apiVersion: v1
kind: Service
metadata:
  name: docker-java-webapp-service
spec:
  type: NodePort
  selector:
    app: docker-java-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007